/*
 * Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

 * 
 * Loyalty Wifi API
 * The Loyalty Boingo Wifi API offers cardholders, via their issuers, the ability to search and connect to Mastercard Global Wifi hotspots around the world through this digital channel. These APIs can be used to build a rich, interactive wifi experience within the issuer's existing mobile or web application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_wifi_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Account
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-07T11:17:22.737-06:00[America/Chicago]")
public class Account {
  public static final String SERIALIZED_NAME_ICA = "ica";
  @SerializedName(SERIALIZED_NAME_ICA)
  private Long ica;

  public static final String SERIALIZED_NAME_PAN = "pan";
  @SerializedName(SERIALIZED_NAME_PAN)
  private String pan;

  public static final String SERIALIZED_NAME_ACCOUNT_TYPE = "accountType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE)
  private String accountType;

  public static final String SERIALIZED_NAME_PRODUCT_TYPE = "productType";
  @SerializedName(SERIALIZED_NAME_PRODUCT_TYPE)
  private String productType;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_PAR = "par";
  @SerializedName(SERIALIZED_NAME_PAR)
  private String par;

  public static final String SERIALIZED_NAME_NAME_ON_CARD = "nameOnCard";
  @SerializedName(SERIALIZED_NAME_NAME_ON_CARD)
  private String nameOnCard;

  public static final String SERIALIZED_NAME_CARD_EXPIRY_DATE = "cardExpiryDate";
  @SerializedName(SERIALIZED_NAME_CARD_EXPIRY_DATE)
  private String cardExpiryDate;

  public static final String SERIALIZED_NAME_CVC_CODE = "cvcCode";
  @SerializedName(SERIALIZED_NAME_CVC_CODE)
  private String cvcCode;

  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  private String brand;

  public static final String SERIALIZED_NAME_PRODUCT_LINE = "productLine";
  @SerializedName(SERIALIZED_NAME_PRODUCT_LINE)
  private String productLine;

  public static final String SERIALIZED_NAME_PRIMARY = "primary";
  @SerializedName(SERIALIZED_NAME_PRIMARY)
  private Boolean primary;

  public static final String SERIALIZED_NAME_CARD_ALIAS = "cardAlias";
  @SerializedName(SERIALIZED_NAME_CARD_ALIAS)
  private String cardAlias;

  public static final String SERIALIZED_NAME_LAST4_PAN = "last4Pan";
  @SerializedName(SERIALIZED_NAME_LAST4_PAN)
  private Integer last4Pan;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private Object object = null;

  public Account ica(Long ica) {
    this.ica = ica;
    return this;
  }

   /**
   * Member ICA code
   * @return ica
  **/
  @ApiModelProperty(example = "12594", value = "Member ICA code")
  public Long getIca() {
    return ica;
  }

  public void setIca(Long ica) {
    this.ica = ica;
  }

  public Account pan(String pan) {
    this.pan = pan;
    return this;
  }

   /**
   * 16 digit account number/credit card number
   * @return pan
  **/
  @ApiModelProperty(example = "5000000000000000", value = "16 digit account number/credit card number")
  public String getPan() {
    return pan;
  }

  public void setPan(String pan) {
    this.pan = pan;
  }

  public Account accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * The type of account. One of SingleMember, JointAccount, FamilyAccount
   * @return accountType
  **/
  @ApiModelProperty(example = "SingleMember", value = "The type of account. One of SingleMember, JointAccount, FamilyAccount")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public Account productType(String productType) {
    this.productType = productType;
    return this;
  }

   /**
   * The type of product
   * @return productType
  **/
  @ApiModelProperty(example = "Black", value = "The type of product")
  public String getProductType() {
    return productType;
  }

  public void setProductType(String productType) {
    this.productType = productType;
  }

  public Account uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * 36 character unique identifier
   * @return uuid
  **/
  @ApiModelProperty(example = "d3459481-fb1c-48bb-8685-40eb629e2ae1", value = "36 character unique identifier")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Account par(String par) {
    this.par = par;
    return this;
  }

   /**
   * payment account reference
   * @return par
  **/
  @ApiModelProperty(example = "q1hjz28rka1ebl470g9xyg90r5d3e", value = "payment account reference")
  public String getPar() {
    return par;
  }

  public void setPar(String par) {
    this.par = par;
  }

  public Account nameOnCard(String nameOnCard) {
    this.nameOnCard = nameOnCard;
    return this;
  }

   /**
   * The full name which is printed on the credit card
   * @return nameOnCard
  **/
  @ApiModelProperty(example = "SALLY CARDHOLDER", value = "The full name which is printed on the credit card")
  public String getNameOnCard() {
    return nameOnCard;
  }

  public void setNameOnCard(String nameOnCard) {
    this.nameOnCard = nameOnCard;
  }

  public Account cardExpiryDate(String cardExpiryDate) {
    this.cardExpiryDate = cardExpiryDate;
    return this;
  }

   /**
   * Expiration date which is printed on the credit card
   * @return cardExpiryDate
  **/
  @ApiModelProperty(example = "02/2024", value = "Expiration date which is printed on the credit card")
  public String getCardExpiryDate() {
    return cardExpiryDate;
  }

  public void setCardExpiryDate(String cardExpiryDate) {
    this.cardExpiryDate = cardExpiryDate;
  }

  public Account cvcCode(String cvcCode) {
    this.cvcCode = cvcCode;
    return this;
  }

   /**
   * CVC code printed on the back of the credit card
   * @return cvcCode
  **/
  @ApiModelProperty(example = "999", value = "CVC code printed on the back of the credit card")
  public String getCvcCode() {
    return cvcCode;
  }

  public void setCvcCode(String cvcCode) {
    this.cvcCode = cvcCode;
  }

  public Account brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Brand of credit card
   * @return brand
  **/
  @ApiModelProperty(example = "Mastercard", value = "Brand of credit card")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public Account productLine(String productLine) {
    this.productLine = productLine;
    return this;
  }

   /**
   * The product line which this credit card belongs to
   * @return productLine
  **/
  @ApiModelProperty(value = "The product line which this credit card belongs to")
  public String getProductLine() {
    return productLine;
  }

  public void setProductLine(String productLine) {
    this.productLine = productLine;
  }

  public Account primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * A Boolean value indicating the &#39;primary&#39; or preferred account. The primary attribute value &#39;true&#39; must appear no more than once.
   * @return primary
  **/
  @ApiModelProperty(example = "true", value = "A Boolean value indicating the 'primary' or preferred account. The primary attribute value 'true' must appear no more than once.")
  public Boolean getPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  public Account cardAlias(String cardAlias) {
    this.cardAlias = cardAlias;
    return this;
  }

   /**
   * A given alias for this credit card
   * @return cardAlias
  **/
  @ApiModelProperty(example = "d3459481-fb1c-48bb-8685-40eb629e2ae1", value = "A given alias for this credit card")
  public String getCardAlias() {
    return cardAlias;
  }

  public void setCardAlias(String cardAlias) {
    this.cardAlias = cardAlias;
  }

   /**
   * Get last4Pan
   * @return last4Pan
  **/
  @ApiModelProperty(example = "0", value = "")
  public Integer getLast4Pan() {
    return last4Pan;
  }

  public void setLast4Pan(Integer last4Pan) {
	this.last4Pan = last4Pan;
}

public Account object(Object object) {
    this.object = object;
    return this;
  }

   /**
   * Extended account object (with localized metadata) for the given product of the requested user.  See Developer Portal (https://developer.mastercard.com/documentation/product-bundle-registration/v1) for additional documentation of the product-specific fields.
   * @return object
  **/
  @ApiModelProperty(example = "{\"accountStatusCode\":\"1\",\"externalMembershipReferenceId\":\"B12345\"}", value = "Extended account object (with localized metadata) for the given product of the requested user.  See Developer Portal (https://developer.mastercard.com/documentation/product-bundle-registration/v1) for additional documentation of the product-specific fields.")
  public Object getObject() {
    return object;
  }

  public void setObject(Object object) {
    this.object = object;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.ica, account.ica) &&
        Objects.equals(this.pan, account.pan) &&
        Objects.equals(this.accountType, account.accountType) &&
        Objects.equals(this.productType, account.productType) &&
        Objects.equals(this.uuid, account.uuid) &&
        Objects.equals(this.par, account.par) &&
        Objects.equals(this.nameOnCard, account.nameOnCard) &&
        Objects.equals(this.cardExpiryDate, account.cardExpiryDate) &&
        Objects.equals(this.cvcCode, account.cvcCode) &&
        Objects.equals(this.brand, account.brand) &&
        Objects.equals(this.productLine, account.productLine) &&
        Objects.equals(this.primary, account.primary) &&
        Objects.equals(this.cardAlias, account.cardAlias) &&
        Objects.equals(this.last4Pan, account.last4Pan) &&
        Objects.equals(this.object, account.object);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ica, pan, accountType, productType, uuid, par, nameOnCard, cardExpiryDate, cvcCode, brand, productLine, primary, cardAlias, last4Pan, object);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    ica: ").append(toIndentedString(ica)).append("\n");
    sb.append("    pan: ").append(toIndentedString(pan)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    productType: ").append(toIndentedString(productType)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    par: ").append(toIndentedString(par)).append("\n");
    sb.append("    nameOnCard: ").append(toIndentedString(nameOnCard)).append("\n");
    sb.append("    cardExpiryDate: ").append(toIndentedString(cardExpiryDate)).append("\n");
    sb.append("    cvcCode: ").append(toIndentedString(cvcCode)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    productLine: ").append(toIndentedString(productLine)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    cardAlias: ").append(toIndentedString(cardAlias)).append("\n");
    sb.append("    last4Pan: ").append(toIndentedString(last4Pan)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

